---
version: '2.2'

networks:
  net_kafka:
    name: net_kafka

volumes:
  cassandra-data:
    driver: local

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.0
    container_name: zookeeper
    networks:
      - net_kafka
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:5.1.0
    container_name: broker
    networks:
      - net_kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 29093:29093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,EXTERNAL_DIFFERENT_HOST://:29093,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:9092,EXTERNAL_SAME_HOST://localhost:29092,EXTERNAL_DIFFERENT_HOST://10.10.10.10:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT,EXTERNAL_DIFFERENT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100

  kafkacat:
    image: confluentinc/cp-kafkacat
    container_name: kafkacat
    command: sleep infinity
    networks:
      - net_kafka

  cassandra:
    image: cassandra:3.11.3
    container_name: cassandra
    networks:
      - net_kafka
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_CLUSTER_NAME=Cassandra"
      - "CASSANDRA_DC=Cassandra"
      - "CASSANDRA_RACK=West"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      - "CASSANDRA_NUM_TOKENS=128"
    restart: on-failure
    volumes:
      - ./cassandra-data:/var/lib/cassandra
      - ./cql:/cql
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-init:
    image: cassandra:3.11.3
    container_name: cassandra-init
    networks:
      - net_kafka
    volumes:
      - ./cql:/cql
    command: /cql/init.sh && /bin/bash
    links:
      - cassandra:db
    depends_on:
      cassandra:
        condition: service_healthy
    restart: on-failure